Dog58/Dog58/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Dog58.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^board/', include('board.urls', namespace='board')),

    url(r'^android/', include('android.urls', namespace='android')),
    url(r'^ckeditor/', include('ckeditor.urls')),

    url(r'', include('gcm.urls')),
    # url(r'', include('gcm.urls')),
)

if settings.DEBUG:
	urlpatterns += patterns('',
		(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
		(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
	)

Dog58/board/urls.py
from django.conf.urls import patterns, url, include
from board import views

urlpatterns = patterns(' ',
	url(r'^$', views.getList, name = 'board'),
	url(r'^(?P<board_id>\d+)/$', views.get, name='get'),
	url(r'^write/$', views.write, name='write'),
	url(r'^save/$', views.save, name='save'),
	url(r'^delete/(?P<board_id>\d+)/$', views.delete, name='delete'),
)

Dog58/board/models.py
from django.db import models
from ckeditor.fields import RichTextField
	 
from PIL import Image
from cStringIO import StringIO
from django.core.files.uploadedfile import SimpleUploadedFile
import os

# Create your models here.
class Board(models.Model) :
	title = models.CharField(max_length=200)
	title_img = models.ImageField(upload_to='./uploads/title/')
    	thumbnail = models.ImageField(upload_to="./uploads/thumbnails/", editable=False,blank=True,null=True)
	content = RichTextField()
	register_date = models.DateTimeField(auto_now_add = True, auto_now = True)
	update_date_start = models.DateTimeField(auto_now=False, auto_now_add=False)
	update_date_end = models.DateTimeField(auto_now=False, auto_now_add=False)
	share_cnt = models.IntegerField(default=0)

	def create_thumbnail(self):
		if not self.title_img:
	             	return

		THUMBNAIL_SIZE = (480,360)
		try :
			DJANGO_TYPE = self.title_img.file.content_type
		except AttributeError :
			return

		if DJANGO_TYPE == 'image/jpeg':
	             	PIL_TYPE = 'jpeg'
			FILE_EXTENSION = 'jpg'
		elif DJANGO_TYPE == 'image/png':
			             PIL_TYPE = 'png'
			             FILE_EXTENSION = 'png'
			 
		image = Image.open(StringIO(self.title_img.read()))
	 
	         	# Convert to RGB if necessary
	         	# Thanks to Limodou on DjangoSnippets.org
	         	# http://www.djangosnippets.org/snippets/20/
	         	#
	         	# I commented this part since it messes up my png files
	         	#
	         	#if image.mode not in ('L', 'RGB'):
	         	#    image = image.convert('RGB')

		image.thumbnail(THUMBNAIL_SIZE, Image.ANTIALIAS)

		temp_handle = StringIO()
		image.save(temp_handle, PIL_TYPE)
		temp_handle.seek(0)

		suf = SimpleUploadedFile(os.path.split(self.title_img.name)[-1],temp_handle.read(),content_type=DJANGO_TYPE)
		self.thumbnail.save('%s_thumbnail.%s'%(os.path.splitext(suf.name)[0],FILE_EXTENSION), suf, save=False)

	def save(self):
		self.create_thumbnail()
		super(Board, self).save()


	
	def __unicode__(self):    
        		return self.title

Dog58/board/forms.py
from django import forms
from board.models import Board
from ckeditor.widgets import CKEditorWidget

class BoardAdminForm(forms.ModelForm):
	content = forms.CharField(label='', widget=CKEditorWidget())
	class Meta:
        		model = Board

Dog58/board/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, render_to_response
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from board.models import Board
from board.forms import BoardAdminForm
from django.template import RequestContext
from django.core.urlresolvers import reverse
# Create your views here.

def  getList(request) :
	boardList = Board.objects.all()
	context = {"boardList" : boardList}
	return render(request, "board/list.html", context)

def get(request, board_id) :
	board = Board.objects.get(id = board_id)
	context = {"content" : board}
	return render(request, "board/content.html", context)

def write(request):
	form = BoardAdminForm()
	tpl  = "board/write.html"
	return render(request, tpl, {"form" : form}) 

def save(request) :
	return HttpResponseRedirect(reverse('board:getList'))

def delete(request, board_id) :
	board = Board.objects.get(id = board_id)
	# try : 
	board.delete()
	# except :
	return HttpResponseRedirect(reverse('board:getList'))

Dog58/templates/board/content.html
{% extends "base.html" %}
{% block content %}
<div id="name" class ="col "> </div>

	<table class="table">
		<thead>
		<tr><th>번호</th><th>제목</th><th>내용</th><th>등록일</th><th>업데이트일</th><th>수정삭제</th></tr>  
		</thead>
		<tbody>
		{% if content %}
	              	<tr>
			              <td><p>{{ content.id }}</p></td>
			              <td>
			                  <p>
			                      	{{ content.title }}
			                  </p>
			              </td>
			              <td>
			                  <p>
			                      	{{ content.content }}
			                  </p>
			              </td>
			              <td><p>{{ content.register_date }}</p></td>
			              <td><p>{{ content.update_date_end }}</p></td>
	              	</tr>
      		{% else %}
          		<p>No Data.</p>
      		{% endif %}
      		</tbody>
 	 </table>

{% endblock %}

Dog58/templates/board/list.html
{% extends "base.html" %}
{% block content %}
	<table class ="table table-hover table-bordered">
		<thead>
			<tr>
				<th>#</th><th>제목</th><th>등록일</th><th>업데이트일</th><th>삭제</th></tr>  
			</tr>
		</thead>
		<tbody>	
		{% if boardList %}
	              	{% for boardRow in boardList %}
	              	<tr>
			              <td><p>{{ boardRow.id }}</p></td>
			              <td><p><a href= "{% url 'board:get' boardRow.id %}" title="">{{ boardRow.title }}</a></p></td>
			              <td><p>{{ boardRow.register_date }}</p></td>
			              <td><p>{{ boardRow.update_date_end }}</p></td>
			              <td><input type=button value="삭제"  OnClick="window.location='./delete/{{ boardRow.id }}'"></td>
	              	</tr>
	             	 {% endfor %}
      		{% else %}
          		<p>No Data.</p>
      		{% endif %}
      		</tbody>
 	 </table>

 	 <table width=700>
		<tr>
			<td><input type=button value="글쓰기"  OnClick="window.location='./write'"></td>
		</tr>
	</table>
{% endblock %}

Dog58/templates/board/write.html
{% extends "base.html" %}
{% block content %}
	<center>
		<form>
			 {{ form.media }}   {{ form.as_p }}

    			<input type="button" value="확인" onClick="{% url 'board:save' %}"/>

		</form>
	</center>
{% endblock %}

<!-- <form name="boardForm" method=post action="{% url 'board:save' %}">
			{% csrf_token %} 
			<table class ="table">
				<tr>
					<td>제목</td>
					<td><input type="text" name="title"></td>
				</tr>
				<tr>
					<td>업데이트 날짜</td>
					<td><input type="text" name="update_date"></td>
				</tr>
				<tr>
					<td>내용</td>
					<td>{{ form.media }}   {{ form.as_p }}</td>
				</tr>
				<tr>
					<td>사진</td>
					<td><input type="text" name="title_img"></td>
				</tr>
			</table>
			<br><br> -->